Repository SpiNNakerManchester/spalloc_server, pull requests merged in 2019-10, with the labels that each got.

#52 Update the versions of SpiNNMan and SpiNNMachine
  requirements.txt
  setup.py
Labels: bug

#49 Version ???
  setup.py
  spalloc_server/_version.py
Labels: enhancement

#50 fixed incorrect import from collections.abc
  count_times.py
  spalloc_server/allocator.py
  spalloc_server/async_bmp_controller.py
  spalloc_server/configuration.py
  spalloc_server/controller.py
  spalloc_server/job_queue.py
  spalloc_server/server.py
  tests/conftest.py
  tests/mock_bmp.py
  tests/test_controller.py
Labels: bug

#53 Pylint
  .pylintrc
  .travis.yml
  spalloc_server/async_bmp_controller.py
  spalloc_server/configuration.py
  spalloc_server/configuration_reloader.py
  spalloc_server/links.py
  spalloc_server/polling_server_core.py
  spalloc_server/server.py
Labels: enhancement, minor
